name: child_info
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  supabase_flutter: ^0.3.3
  timeago: ^3.3.0
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^10.2.1
  auto_size_text: ^3.0.0
  json_path: ^0.4.2
  page_transition: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true